site_name: Artificial Primary Care Data 
nav:
  - Home: index.md
  - Users: users.md
  - Devs: dev.md
  - Java: java.md
  - Example Outputs: outputs.md
theme: 
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  - tables
  - footnotes